
require(Matrix)
require(S4Vectors)
require(SummarizedExperiment)
require(celldex)

.singler_path <- function(x) paste("singler", x, sep = "/")

source(.singler_path("aggregate-reference.R"))
source(.singler_path("classify-singler.R"))
source(.singler_path("combine-common-result.R"))
source(.singler_path("combine-recompute-result.R"))
source(.singler_path("cpp.R"))
source(.singler_path("delta-from-median.R"))
source(.singler_path("get-classic-markers.R"))
source(.singler_path("match-reference.R"))
source(.singler_path("mock-data.R"))
source(.singler_path("plot-delta-dist.R"))
source(.singler_path("plot-score-dist.R"))
source(.singler_path("plot-score-hmap.R"))
source(.singler_path("prune-scores.R"))
source(.singler_path("rebuild-indices.R"))
source(.singler_path("utils.R"))
source(.singler_path("train-singler.R"))
source(.singler_path("singler.R"))
